//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public short ServiceCategoryId { get; set; }
        public long LocationId { get; set; }
        public long ConsultantId { get; set; }
        public string Note { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerEmail { get; set; }
    
        public virtual ClientLocation ClientLocation { get; set; }
        public virtual Consultant Consultant { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
    }
}
