//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallToPhoneAddress
    {
        public long CallToPhoneAddressId { get; set; }
        public string CallSId { get; set; }
        public long CallPhoneAddressId { get; set; }
    
        public virtual Call Call { get; set; }
        public virtual CallPhoneAddress CallPhoneAddress { get; set; }
    }
}
