//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Call()
        {
            this.CallActions = new HashSet<CallAction>();
            this.CallFromPhoneAddresses = new HashSet<CallFromPhoneAddress>();
            this.CallGathers = new HashSet<CallGather>();
            this.CallGatherAttempts = new HashSet<CallGatherAttempt>();
            this.CallSurveyAnswers = new HashSet<CallSurveyAnswer>();
            this.CallToPhoneAddresses = new HashSet<CallToPhoneAddress>();
        }
    
        public string CallSid { get; set; }
        public System.DateTime DateTimeReceived { get; set; }
        public long CallFlowId { get; set; }
        public string AccountSid { get; set; }
        public string FromPhoneNumber { get; set; }
        public string ToPhoneNUmber { get; set; }
        public short CallStatus { get; set; }
        public short Direction { get; set; }
        public string ApiVersion { get; set; }
        public string ForwardedFrom { get; set; }
        public string CallerName { get; set; }
        public string ParentCallSid { get; set; }
    
        public virtual CallDirection CallDirection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallAction> CallActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallFromPhoneAddress> CallFromPhoneAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallGather> CallGathers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallGatherAttempt> CallGatherAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallSurveyAnswer> CallSurveyAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallToPhoneAddress> CallToPhoneAddresses { get; set; }
    }
}
