//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallFlowStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallFlowStep()
        {
            this.CallFlowStepGatherRetries = new HashSet<CallFlowStepGatherRetry>();
            this.CallFlowStepOptions = new HashSet<CallFlowStepOption>();
            this.CallGathers = new HashSet<CallGather>();
        }
    
        public long CallFlowStepId { get; set; }
        public long CallFlowId { get; set; }
        public short CallFlowStepType { get; set; }
        public bool IsWelcomeStep { get; set; }
    
        public virtual CallFlow CallFlow { get; set; }
        public virtual CallFlowStepType CallFlowStepType1 { get; set; }
        public virtual CallFlowStepDial CallFlowStepDial { get; set; }
        public virtual CallFlowStepGather CallFlowStepGather { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallFlowStepGatherRetry> CallFlowStepGatherRetries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallFlowStepOption> CallFlowStepOptions { get; set; }
        public virtual CallFlowStepSay CallFlowStepSay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallGather> CallGathers { get; set; }
    }
}
