//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallAction
    {
        public long CallActionId { get; set; }
        public System.DateTime ActionDateTime { get; set; }
        public string CallSid { get; set; }
        public string ActionDescription { get; set; }
    
        public virtual Call Call { get; set; }
    }
}
