//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallSurveyAnswer
    {
        public long CallSurveyAnswerId { get; set; }
        public string CallSid { get; set; }
        public long CallSurveyQuestionId { get; set; }
        public string SurveyAnswer { get; set; }
    
        public virtual Call Call { get; set; }
        public virtual CallSurveyQuestion CallSurveyQuestion { get; set; }
    }
}
