//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallFlowStepOption
    {
        public long CallFlowStepOptionId { get; set; }
        public long CallFlowStepId { get; set; }
        public string OptionDescription { get; set; }
        public string OptionValue { get; set; }
        public long NextCallFlowStepId { get; set; }
    
        public virtual CallFlowStep CallFlowStep { get; set; }
        public virtual CallFlowStepGather CallFlowStepGather { get; set; }
    }
}
