//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallFlowStepGather
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallFlowStepGather()
        {
            this.CallFlowStepOptions = new HashSet<CallFlowStepOption>();
            this.CallGatherAttempts = new HashSet<CallGatherAttempt>();
            this.CallSurveyQuestions = new HashSet<CallSurveyQuestion>();
        }
    
        public long CallFlowStepId { get; set; }
        public string GatherName { get; set; }
        public short Attempts { get; set; }
    
        public virtual CallFlowStep CallFlowStep { get; set; }
        public virtual CallFlowStepGatherRetry CallFlowStepGatherRetry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallFlowStepOption> CallFlowStepOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallGatherAttempt> CallGatherAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallSurveyQuestion> CallSurveyQuestions { get; set; }
    }
}
