//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallGatherAttempt
    {
        public long CallGatherAttemptId { get; set; }
        public string CallSid { get; set; }
        public long CallFlowStepId { get; set; }
        public short Attempts { get; set; }
    
        public virtual Call Call { get; set; }
        public virtual CallFlowStepGather CallFlowStepGather { get; set; }
    }
}
