//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tollfree
    {
        public long TollfreeId { get; set; }
        public string TollfreeNumber { get; set; }
        public long CallFlowId { get; set; }
    
        public virtual CallFlow CallFlow { get; set; }
    }
}
